name: Build and Export Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-evalplus

    steps:
      - name: Checkout only feature/nothink branch
        uses: actions/checkout@v4
        with:
          ref: feature/nothink
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Save Docker image to tar
        run: |
          docker save ${{ env.IMAGE_NAME }}:latest -o ${{ env.IMAGE_NAME }}.tar

      - name: Upload artifact (Docker image tar)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.IMAGE_NAME }}.tar
